name: Go
on:
  push:
    branches:
      - zdns
      - master
  pull_request:
    branches:
      - zdns
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  # Only tag releases off the zdns branch
  release:
    if: ${{ github.ref == 'refs/heads/zdns' }}
    needs: build
    name: Release Next Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Latest Tag for zdns
      id: get_tag
      shell: bash
      run: |
        LATEST_TAG=$(git tag --merged | sort -V | tail -n 1); \
        echo ${LATEST_TAG}; \
        if [[ "${LATEST_TAG}" == *-zdns-* ]] || [[ "${LATEST_TAG}" == *-zdns ]]; then \
            if [[ "${LATEST_TAG}" == *-zdns ]]; then \
                echo "modifying tag to match new syntax"; \
                LATEST_TAG="${LATEST_TAG}-0"; \
            fi; \
            echo "already tagged a release here, using next version"; \
            ZDNS_RELEASE_NUM=$(echo ${LATEST_TAG} | sed 's|.*-zdns-\(.*\)|\1|'); \
            ZDNS_RELEASE_NUM=$((ZDNS_RELEASE_NUM+1)); \
            echo $ZDNS_RELEASE_NUM; \
            TAG_PORTION=$(echo ${LATEST_TAG} | sed 's|\(.*\)-zdns-.*|\1|'); \
            echo $TAG_PORTION; \
            ZDNS_TAG="${TAG_PORTION}-zdns-${ZDNS_RELEASE_NUM}"; \
            echo $ZDNS_TAG; \
        else \
            echo "cleared hot"; \
            ZDNS_TAG="${LATEST_TAG}-zdns-0"; \
            echo $ZDNS_TAG; \
        fi; \
        echo "::set-output name=ZDNS_TAG::${ZDNS_TAG}";
    - name: Release Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get_tag.outputs.ZDNS_TAG }}
        release_branches: zdns
        tag_prefix: ""
        dry_run: true